language: ru

pipeline:
- name: WhitespaceTokenizer
  intent_tokenization_flag: true

- name: LexicalSyntacticFeaturizer

- name: CountVectorsFeaturizer
  analyzer: "word"
  min_ngram: 1
  max_ngram: 2

- name: DIETClassifier
  epochs: 150
  intent_classification:
    confidence_threshold: 0.7
  entity_recognition:
    confidence_threshold: 0.75

- name: FallbackClassifier
  threshold: 0.35
  ambiguity_threshold: 0.15

policies:
- name: MemoizationPolicy
  max_history: 3

- name: RulePolicy
  core_fallback_threshold: 0.45
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: false    # Ключевой параметр против зацикливания

- name: TEDPolicy
  max_history: 5
  epochs: 200
  confidence_threshold: 0.6

augmentation:
- "random_word_swap"
- "random_word_drop"
- "random_word_insert"

augmentation_factor: 20

config_version: 3.1
assistant_id: 20250515-211413-tempered-bakery
